spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:querydsl
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
